server:
  port: 80
####服务网关名称
spring:
  application:
    name: GatewayServer
  cloud:
    gateway:
      ###路由策略
      enabled: true
      routes:
        ###根据我们的服务名称查找地址实现调用
        - id: GatewayServer
          ####转发http://129.204.22.71:8888/
          uri: lb://ProduceService/
          #匹配规则
          predicates:
            - Path=/**
            - Path=/setService/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

