server:
  port: 80
####服务网关名称
spring:
  application:
    name: GatewayServer
  cloud:
    gateway:
      ###路由策略
      routes:
        ###根据我们的服务名称查找地址实现调用
        - id: GatewayServer
          ####转发http://www.mayikt.com/
          uri: http://129.204.22.71:8888/
          predicates:
            - Path=/GatewayServer/**
