server:
  port: 8085
  tomcat:
    max-threads: 20
spring:
  application:
    name: ProduceService
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sentinel:
    transport:
      dashboard: 127.0.0.1:8719
    eager: true
